---
# file: set_ssh_config.yml
- name: set_ssh_config
  hosts: localhost

  tasks:
    - name: enable ssh AuthorizedKeysFile
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#AuthorizedKeysFile"
        line: "AuthorizedKeysFile      .ssh/authorized_keys"
        state: present
        backrefs: yes
        backup: yes
      notify:
        - restart ssh

    - name: enable ssh PubkeyAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#PubkeyAuthentication yes"
        line: "PubkeyAuthentication yes"
        state: present
        backrefs: yes
        backup: yes
      notify:
        - restart ssh

    - name: disable ssh PasswordAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
        state: present
        backrefs: yes
        backup: yes
      notify:
        - restart ssh

    - name: enable ssh PasswordAuthentication for user deploy
      lineinfile:
        path: /etc/ssh/sshd_config
        insertafter: EOF
        line: "{{ item }}"
        state: present
        backup: yes
      with_items:
        - "Match User deploy"
        - "        PasswordAuthentication yes"
      notify:
        - restart ssh

    - name: disable ssh UsePAM
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^UsePAM yes"
        line: "UsePAM no"
        state: present
        backrefs: yes
        backup: yes
      notify:
        - restart ssh

    - name: disable ssh PermitEmptyPasswords
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#PermitEmptyPasswords no"
        line: "PermitEmptyPasswords no"
        state: present
        backrefs: yes
        backup: yes
      notify:
        - restart ssh

    - name: disable ssh PermitRootLogin
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#PermitRootLogin prohibit-password"
        line: "PermitRootLogin prohibit-password"
        state: present
        backrefs: yes
        backup: yes
      notify:
        - restart ssh

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted